version: "3.9"

services:
  app_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev-backend
    command: poetry run uvicorn app.main:make_app --factory --host=0.0.0.0 --port=8080 --reload
    env_file:
      - .env.app
      - .env.db
    volumes:
      - ./backend/app:/backend/app
      - ./backend/alembic:/backend/alembic
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    command: [ "postgres" , "-c", "log_statement=all" ]
    env_file:
      - .env.db
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: