version: "3.9"

services:
  app_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev-backend
    command: ./docker-entrypoint.sh
    env_file:
      - backend/.env.app.dev
      - backend/.env.db.dev
    volumes:
      - ./backend/app:/backend/app
      - ./backend/alembic:/backend/alembic
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    command: [ "postgres" , "-c", "log_statement=all" ]
    env_file:
      - backend/.env.db.dev
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: