"""remove relations

Revision ID: 2051f2459d47
Revises: bed2bfeca773
Create Date: 2023-10-20 13:32:11.114204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2051f2459d47'
down_revision = 'bed2bfeca773'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
