"""ondelete Cascade

Revision ID: bed2bfeca773
Revises: 5ae5a596d406
Create Date: 2023-05-19 13:01:53.121419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bed2bfeca773'
down_revision = '5ae5a596d406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('tasks_category_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_category_id_fkey', 'tasks', 'categories', ['category_id'], ['id'])
    op.alter_column('tasks', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
